server:
  port: 0
spring:
  active: '@activatedProperties@'
  datasource:
    url: jdbc:postgresql://database-2.cn0tlrtsmlxe.us-east-1.rds.amazonaws.com:5432/postgres
    currentSchema: public
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true
    validateMigrationNaming: true
clickBank:
  host: https://api.clickbank.net
  path: graphql
  service:
    name: clickbank
uberSuggest:
  host: https://app.neilpatel.com
  path: api
  service:
    name: neilpatel