server:
  port: 0
spring:
  application:
    name: product-identifier-service
  datasource:
    url: jdbc:postgresql://localhost:5432/produtosMK
    currentSchema: public
    username: mkdigital
    password: mkdigital
    driver-class-name: org.postgresql.Driver
    hikari:
      poolName: Hikari
      auto-commit: false
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
      maximum-pool-size: 100
      minimum-idle: 10
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true
    validateMigrationNaming: true
clickBank:
  host: https://api.clickbank.net
  path: graphql
  service:
    name: clickbank
uberSuggest:
  host: https://app.neilpatel.com
  path: api
  service:
    name: neilpatel
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}