spring:
  active: '@activatedProperties@'
  datasource:
    url: ${JDBC_DATASOURCE_URL}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update

oddspedia:
  host: https://oddspedia.com/api
  path: v1
  service:
    name: oddspedia