logging:
  file:
    name: ./logs/log-file.log
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
server:
  port: 8082
spring:
  application:
    name: product-identifier-service
  datasource:
    url: jdbc:postgresql://auth-service.cn0tlrtsmlxe.us-east-1.rds.amazonaws.com:5432/products
    username: products_identifier
    password: bvBb8RMCF9mJZMNEtjxyPqnF7gEYgSncKHQx
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    validateMigrationNaming: true
management:
  endpoint:
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka.botisistemas.com.br/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}