spring:
  active: '@activatedProperties@'
  datasource:
    url: jdbc:postgresql://database-2.cn0tlrtsmlxe.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update

clickBank:
  host: https://api.clickbank.net
  path: graphql
  service:
    name: clickbank