
INSERT INTO public.category VALUES (nextval('category_id'),'Reference');
INSERT INTO public.category VALUES (nextval('category_id'),'Sports');
INSERT INTO public.category VALUES (nextval('category_id'),'Self-Help');
INSERT INTO public.category VALUES (nextval('category_id'),'Green Products');
INSERT INTO public.category VALUES (nextval('category_id'),'Software & Services');
INSERT INTO public.category VALUES (nextval('category_id'),'Employment & Jobs');
INSERT INTO public.category VALUES (nextval('category_id'),'Home & Garden');
INSERT INTO public.category VALUES (nextval('category_id'),'Arts & Entertainment');
INSERT INTO public.category VALUES (nextval('category_id'),'Business / Investing');
INSERT INTO public.category VALUES (nextval('category_id'),'Mobile');
INSERT INTO public.category VALUES (nextval('category_id'),'Spirituality, New Age & Alternative Beliefs');
INSERT INTO public.category VALUES (nextval('category_id'),'Travel');
INSERT INTO public.category VALUES (nextval('category_id'),'Parenting & Families');
INSERT INTO public.category VALUES (nextval('category_id'),'Languages');
INSERT INTO public.category VALUES (nextval('category_id'),'Betting Systems');
INSERT INTO public.category VALUES (nextval('category_id'),'Cooking, Food & Wine');
INSERT INTO public.category VALUES (nextval('category_id'),'Health & Fitness');
INSERT INTO public.category VALUES (nextval('category_id'),'Fiction');
INSERT INTO public.category VALUES (nextval('category_id'),'Computers / Internet');
INSERT INTO public.category VALUES (nextval('category_id'),'E-business & E-marketing');
INSERT INTO public.category VALUES (nextval('category_id'),'Politics / Current Events');
INSERT INTO public.category VALUES (nextval('category_id'),'Games');
INSERT INTO public.category VALUES (nextval('category_id'),'Education');

INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Art',(select id from category where category.category = 'Arts & Entertainment'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Body Art',(select id from category where category.category = 'Arts & Entertainment'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Dance',(select id from category where category.category = 'Arts & Entertainment'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Fashion',(select id from category where category.category = 'Arts & Entertainment'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Film & Television',(select id from category where category.category = 'Arts & Entertainment'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'General',(select id from category where category.category = 'Arts & Entertainment'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Magic Tricks',(select id from category where category.category = 'Arts & Entertainment'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Music',(select id from category where category.category = 'Arts & Entertainment'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Photography',(select id from category where category.category = 'Arts & Entertainment'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Casino Table Games',(select id from category where category.category = 'Betting Systems'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Football',(select id from category where category.category = 'Betting Systems'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'General',(select id from category where category.category = 'Betting Systems'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Horse Racing',(select id from category where category.category = 'Betting Systems'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Poker',(select id from category where category.category = 'Betting Systems'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Soccer',(select id from category where category.category = 'Betting Systems'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Careers, Industries & Professions',(select id from category where category.category = 'Business / Investing'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Commodities',(select id from category where category.category = 'Business / Investing'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Derivatives',(select id from category where category.category = 'Business / Investing'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Economics',(select id from category where category.category = 'Business / Investing'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Equities & Stocks',(select id from category where category.category = 'Business / Investing'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Foreign Exchange',(select id from category where category.category = 'Business / Investing'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'General',(select id from category where category.category = 'Business / Investing'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'International Business',(select id from category where category.category = 'Business / Investing'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Management & Leadership',(select id from category where category.category = 'Business / Investing'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Marketing & Sales',(select id from category where category.category = 'Business / Investing'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Personal Finance',(select id from category where category.category = 'Business / Investing'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Real Estate',(select id from category where category.category = 'Business / Investing'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Small Biz / Entrepreneurship',(select id from category where category.category = 'Business / Investing'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Databases',(select id from category where category.category = 'Computers / Internet'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'General',(select id from category where category.category = 'Computers / Internet'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Graphics',(select id from category where category.category = 'Computers / Internet'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Hardware',(select id from category where category.category = 'Computers / Internet'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Networking',(select id from category where category.category = 'Computers / Internet'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Programming',(select id from category where category.category = 'Computers / Internet'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Software',(select id from category where category.category = 'Computers / Internet'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Web Hosting',(select id from category where category.category = 'Computers / Internet'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Web Site Design',(select id from category where category.category = 'Computers / Internet'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'BBQ',(select id from category where category.category = 'Cooking, Food & Wine'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Baking',(select id from category where category.category = 'Cooking, Food & Wine'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Cooking',(select id from category where category.category = 'Cooking, Food & Wine'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Drinks & Beverages',(select id from category where category.category = 'Cooking, Food & Wine'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'General',(select id from category where category.category = 'Cooking, Food & Wine'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Recipes',(select id from category where category.category = 'Cooking, Food & Wine'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Special Diet',(select id from category where category.category = 'Cooking, Food & Wine'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Special Occasions',(select id from category where category.category = 'Cooking, Food & Wine'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Vegetables / Vegetarian',(select id from category where category.category = 'Cooking, Food & Wine'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Affiliate Marketing',(select id from category where category.category = 'E-business & E-marketing'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Article Marketing',(select id from category where category.category = 'E-business & E-marketing'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Banners',(select id from category where category.category = 'E-business & E-marketing'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Blog Marketing',(select id from category where category.category = 'E-business & E-marketing'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Consulting',(select id from category where category.category = 'E-business & E-marketing'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Copywriting',(select id from category where category.category = 'E-business & E-marketing'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'E-commerce Operations',(select id from category where category.category = 'E-business & E-marketing'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Email Marketing',(select id from category where category.category = 'E-business & E-marketing'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'General',(select id from category where category.category = 'E-business & E-marketing'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Marketing',(select id from category where category.category = 'E-business & E-marketing'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Niche Marketing',(select id from category where category.category = 'E-business & E-marketing'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Promotion',(select id from category where category.category = 'E-business & E-marketing'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'SEM & SEO',(select id from category where category.category = 'E-business & E-marketing'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Social Media Marketing',(select id from category where category.category = 'E-business & E-marketing'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Video Marketing',(select id from category where category.category = 'E-business & E-marketing'));

INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Admissions',(select id from category where category.category = 'Education'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Educational Materials',(select id from category where category.category = 'Education'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Higher Education',(select id from category where category.category = 'Education'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'K-12',(select id from category where category.category = 'Education'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Test Prep & Study Guides',(select id from category where category.category = 'Education'));

INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Cover Letter & Resume Guides',(select id from category where category.category = 'Employment & Jobs'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'General',(select id from category where category.category = 'Employment & Jobs'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Job Listings',(select id from category where category.category = 'Employment & Jobs'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Job Search Guides',(select id from category where category.category = 'Employment & Jobs'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Job Skills / Training',(select id from category where category.category = 'Employment & Jobs'));

INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'General',(select id from category where category.category = 'Fiction'));

INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Console Guides & Repairs',(select id from category where category.category = 'Games'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'General',(select id from category where category.category = 'Games'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Strategy Guides',(select id from category where category.category = 'Games'));

INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Alternative Energy',(select id from category where category.category = 'Green Products'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Conservation & Efficiency',(select id from category where category.category = 'Green Products'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'General',(select id from category where category.category = 'Green Products'));

INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Addiction',(select id from category where category.category = 'Health & Fitness'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Beauty',(select id from category where category.category = 'Health & Fitness'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Dental Health',(select id from category where category.category = 'Health & Fitness'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Dietary Supplements',(select id from category where category.category = 'Health & Fitness'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Diets & Weight Loss',(select id from category where category.category = 'Health & Fitness'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Exercise & Fitness',(select id from category where category.category = 'Health & Fitness'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'General',(select id from category where category.category = 'Health & Fitness'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Meditation',(select id from category where category.category = 'Health & Fitness'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Men''s Health',(select id from category where category.category = 'Health & Fitness'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Mental Health',(select id from category where category.category = 'Health & Fitness'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Nutrition',(select id from category where category.category = 'Health & Fitness'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Remedies',(select id from category where category.category = 'Health & Fitness'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Sleep and Dreams',(select id from category where category.category = 'Health & Fitness'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Spiritual Health',(select id from category where category.category = 'Health & Fitness'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Strength Training',(select id from category where category.category = 'Health & Fitness'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Women''s Health',(select id from category where category.category = 'Health & Fitness'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Yoga',(select id from category where category.category = 'Health & Fitness'));


INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Animal Care & Pets',(select id from category where category.category = 'Home & Garden'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Crafts & Hobbies',(select id from category where category.category = 'Home & Garden'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Gardening & Horticulture',(select id from category where category.category = 'Home & Garden'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'General',(select id from category where category.category = 'Home & Garden'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Homebuying',(select id from category where category.category = 'Home & Garden'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'How-to & Home Improvements',(select id from category where category.category = 'Home & Garden'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Interior Design',(select id from category where category.category = 'Home & Garden'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Weddings',(select id from category where category.category = 'Home & Garden'));

INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Arabic',(select id from category where category.category = 'Languages'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'English',(select id from category where category.category = 'Languages'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Hebrew',(select id from category where category.category = 'Languages'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Japanese',(select id from category where category.category = 'Languages'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Other',(select id from category where category.category = 'Languages'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Spanish',(select id from category where category.category = 'Languages'));


INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Developer Tools',(select id from category where category.category = 'Mobile'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'General',(select id from category where category.category = 'Mobile'));

INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Divorce',(select id from category where category.category = 'Parenting & Families'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Education',(select id from category where category.category = 'Parenting & Families'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Genealogy',(select id from category where category.category = 'Parenting & Families'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'General',(select id from category where category.category = 'Parenting & Families'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Marriage',(select id from category where category.category = 'Parenting & Families'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Parenting',(select id from category where category.category = 'Parenting & Families'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Pregnancy & Childbirth',(select id from category where category.category = 'Parenting & Families'));

INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Automotive',(select id from category where category.category = 'Reference'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Catalogs & Directories',(select id from category where category.category = 'Reference'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Consumer Guides',(select id from category where category.category = 'Reference'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Education',(select id from category where category.category = 'Reference'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Gay / Lesbian',(select id from category where category.category = 'Reference'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'General',(select id from category where category.category = 'Reference'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Law & Legal Issues',(select id from category where category.category = 'Reference'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'The Sciences',(select id from category where category.category = 'Reference'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Writing',(select id from category where category.category = 'Reference'));

INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Dating Guides',(select id from category where category.category = 'Self-Help'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'General',(select id from category where category.category = 'Self-Help'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Marriage & Relationships',(select id from category where category.category = 'Self-Help'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Motivational / Transformational',(select id from category where category.category = 'Self-Help'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Personal Finance',(select id from category where category.category = 'Self-Help'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Public Speaking',(select id from category where category.category = 'Self-Help'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Self Defense',(select id from category where category.category = 'Self-Help'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Self-Esteem',(select id from category where category.category = 'Self-Help'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Stress Management',(select id from category where category.category = 'Self-Help'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Success',(select id from category where category.category = 'Self-Help'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Survival',(select id from category where category.category = 'Self-Help'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Time Management',(select id from category where category.category = 'Self-Help'));


INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Background Investigations',(select id from category where category.category = 'Software & Services'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Digital Photos',(select id from category where category.category = 'Software & Services'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Education',(select id from category where category.category = 'Software & Services'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Email',(select id from category where category.category = 'Software & Services'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Foreign Exchange Investing',(select id from category where category.category = 'Software & Services'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'General',(select id from category where category.category = 'Software & Services'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Graphic Design',(select id from category where category.category = 'Software & Services'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Internet Tools',(select id from category where category.category = 'Software & Services'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'MP3 & Audio',(select id from category where category.category = 'Software & Services'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Productivity',(select id from category where category.category = 'Software & Services'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'System Optimization',(select id from category where category.category = 'Software & Services'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Utilities',(select id from category where category.category = 'Software & Services'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Video',(select id from category where category.category = 'Software & Services'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Astrology',(select id from category where category.category = 'Spirituality, New Age & Alternative Beliefs'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'General',(select id from category where category.category = 'Spirituality, New Age & Alternative Beliefs'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Hypnosis',(select id from category where category.category = 'Spirituality, New Age & Alternative Beliefs'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Magic',(select id from category where category.category = 'Spirituality, New Age & Alternative Beliefs'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Numerology',(select id from category where category.category = 'Spirituality, New Age & Alternative Beliefs'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Paranormal',(select id from category where category.category = 'Spirituality, New Age & Alternative Beliefs'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Psychics',(select id from category where category.category = 'Spirituality, New Age & Alternative Beliefs'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Religion',(select id from category where category.category = 'Spirituality, New Age & Alternative Beliefs'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Tarot',(select id from category where category.category = 'Spirituality, New Age & Alternative Beliefs'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Witchcraft',(select id from category where category.category = 'Spirituality, New Age & Alternative Beliefs'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Automotive',(select id from category where category.category = 'Sports'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Baseball',(select id from category where category.category = 'Sports'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Basketball',(select id from category where category.category = 'Sports'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Cycling',(select id from category where category.category = 'Sports'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'General',(select id from category where category.category = 'Sports'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Golf',(select id from category where category.category = 'Sports'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Hockey',(select id from category where category.category = 'Sports'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Martial Arts',(select id from category where category.category = 'Sports'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Outdoors & Nature',(select id from category where category.category = 'Sports'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Racket Sports',(select id from category where category.category = 'Sports'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Running',(select id from category where category.category = 'Sports'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Soccer',(select id from category where category.category = 'Sports'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Training',(select id from category where category.category = 'Sports'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Water Sports',(select id from category where category.category = 'Sports'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Winter Sports',(select id from category where category.category = 'Sports'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Europe',(select id from category where category.category = 'Travel'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'General',(select id from category where category.category = 'Travel'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'Specialty Travel',(select id from category where category.category = 'Travel'));
INSERT INTO public.sub_category (id,sub_category, category_id) VALUES (nextval('subcategory_id'),'United States',(select id from category where category.category = 'Travel'));

