name: Build and Deploy
on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]    

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build and Package Maven
        run: mvn clean package -DskipTests -B

      - name: Upload Artifact to s3
        run: |
            sudo apt-get install -y zip
            zip -r products.zip target/*.jar scripts/*.sh appspec.yml pom.xml
            aws s3 cp products.zip s3://${{ secrets.AWS_DEPLOY_BUCKET }}/
      
  deploy:
    name: Deploying on AWS  
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET }}
        aws-region: ${{ secrets.AWS_REGION }} 

    - name: Deploying
      run: |
        create_deploy() {
          echo $(
                aws deploy create-deployment \
                --application-name ${{ secrets.AWS_CODEDEPOY_APP_NAME }} \
                --deployment-group-name ${{ secrets.AWS_CODEDEPOY_GROUP_NAME }} \
                --deployment-config-name CodeDeployDefault.OneAtATime \
                --s3-location bucket=${{ secrets.AWS_DEPLOY_BUCKET }},key=products.zip,bundleType=zip | jq -r '.deploymentId'
          )
        }
        deploy_waiter() {
          aws deploy wait deployment-successful --deployment-id $1
        }
        deployment_id=$(create_deploy)
        echo "deploymentId: ${deployment_id}"
        deploy_waiter ${deployment_id}